// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3L-qJ96EyMiWyMZ9yjjVEq9FY4-nF0-Q',
    appId: '1:712540422645:web:ed51c2ac2958fbeade60bc',
    messagingSenderId: '712540422645',
    projectId: 'fir-tcc-bd287',
    authDomain: 'fir-tcc-bd287.firebaseapp.com',
    storageBucket: 'fir-tcc-bd287.appspot.com',
    measurementId: 'G-405SVR84KD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhN5Z__2T-IdiWTHBA851Nq0RPmZb_cis',
    appId: '1:712540422645:android:97369a13af7389f8de60bc',
    messagingSenderId: '712540422645',
    projectId: 'fir-tcc-bd287',
    storageBucket: 'fir-tcc-bd287.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEn0XNHYEgMYtF3WoeXtr6DW8799sZ-V4',
    appId: '1:712540422645:ios:168eb7391915771bde60bc',
    messagingSenderId: '712540422645',
    projectId: 'fir-tcc-bd287',
    storageBucket: 'fir-tcc-bd287.appspot.com',
    iosClientId: '712540422645-hpjndgi8huchs5j1213am18oubjatk0c.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterEstudo',
  );
}
